export const motivationsPhrases = [
	'Todos os dias são uma oportunidade para recomeçar e para planejar um novo caminho. Siga com fé e acredite em você.',
	'A palavra “impossível” foi inventada para ser desafiada.',
	'Somos capazes de fazer muito mais do que imaginamos!',
	'Nós somos como o clima: feitos de dias de chuva e de sol!',
	'Há ainda tanta coisa linda na vida para se descobrir.',
	'Que todos os nossos passos nos levem para o que nos faz feliz de verdade.',
	'Abra os olhos e aventure-se nessa jornada chamada vida!',
	'Há tantas pessoas que torcem por você na vida.',
	'Os dias difíceis são a forma mais rápida de aprendermos a apreciar os bons.',
	'Siga sempre confiante do seu potencial!',
	'Hoje é um novo dia. Não fique pensando no ontem.',
	'A coragem está um passo à frente do medo.',
	'Os sonhos são a melhor forma de termos uma direção na vida e um motivo para caminhar.',
	'A vitalidade é demonstrada não apenas pela persistência, mas pela capacidade de começar de novo.',
	'Só se pode alcançar um grande êxito quando nos mantemos fiéis a nós mesmos.',
	'Lute com determinação, abrace a vida com paixão, perca com classe e vença com ousadia, porque o mundo pertence a quem se atreve e a vida é muito para ser insignificante.',
	'Receita para uma boa semana: acredite em você e trate o seu corpo com carinho.',
	'Quando tudo parecer impossível, é sinal de que está precisando de uns bons dias de descanso para aliviar a pressão e liberar a sua mente. Depois, verá que os problemas nem eram tão grandes assim.',
	'Não se torture quando as coisas não ocorrerem como você planejou. Os planos nos ajudam a traçar o caminho, mas é normal que tenhamos que mudá-los depois!',
	'Comece fazendo o que é necessário, depois o que é possível, e de repente você estará fazendo o impossível.',
	'Não há a necessidade de caminhar rápido. Apenas siga caminhando.',
	'A força não provém da capacidade física. Provém de uma vontade indomável.',
	'Se aquela meta antiga já não te faz mais feliz, elimine-a sem dó!',
	'Não precisamos conquistar o mundo todos os dias!',
	'Dias complicados fazem parte. O bom é que passam e depois aparecem dias bons.',
	'A vida é como uma montanha: tem altos e baixos, exige caminhada e tem paisagens para se observar durante todo o caminho.',
	'Respeite seu corpo e trate com carinho a sua mente.',
	'Em meio ao caos, respire fundo.',
	'Acredite em si próprio e chegará um dia em que os outros não terão outra escolha senão acreditar com você.',
	'Os nossos sonhos são umas das melhores coisas que moram dentro de nós.',
	'Transportai um punhado de terra todos os dias e fareis uma montanha.',
	'Você é forte, você consegue.',
	'Se hoje fosse a primeira página do seu livro da vida, como você gostaria de começar com ela?',
	'Não existem batalhas impossíveis para quem está disposto a nunca desistir.',
	'Algumas coisas ruins acontecem para aprendermos a ficar mais fortes.',
	'Nunca é tarde para fazer o que ainda movimenta os seus sonhos.',
	'Gostaria que você soubesse que existe dentro de si uma força capaz de mudar sua vida. Basta que lute e aguarde um novo amanhecer.',
	'A única forma de chegar ao impossível é acreditar que é possível.',
	'A vida se contrai e se expande proporcionalmente à coragem do indivíduo.',
	'Os nossos maiores medos também podem ser nossos maiores impulsos para novas conquistas.',
	'Não desista de algo quando falarem que você não é capaz. Levante-se e mostre que estão enganados.',
	'Mudar é bom! Aprenda a se redescobrir.',
	'Há tanta coisa incrível para descobrir sobre você. Desafie-se e permita-se conhecer diferentes lados de você.',
	'Algumas caminhadas precisam ser iniciadas sem ninguém ao lado. Ao longo do caminho, algumas pessoas vão se juntar a você. Fique tranquilo.',
	'Você precisa fazer aquilo que pensa que não é capaz de fazer.',
	'Cuide-se como se você fosse de ouro, ponha-se você mesmo de vez em quando numa redoma e poupe-se.',
	'Para navegar contra a corrente são necessárias condições raras: espírito de aventura, coragem, perseverança e paixão.',
	'Seja um borboleta e passe por uma bela metamorfose!',
	'A primavera virá dentro de você. Aguente firme.',
	'Você já fez uma caminhada tão bonita até agora. Parabenize-se.',
	'Hoje a meta do dia é ter gratidão pela vida e se parabenizar por tudo o que você já fez.',
	'Um dia você estará olhando para trás e pensando em todas as conquistas que já fez.',
	'Não coloque metas muito pesadas no seu caminho. Ninguém merece sofrer com um peso desnecessário nas costas!',
	'Faça as pazes com a vida e ande de mãos dadas com ela.',
	'Ter sucesso é estar em paz com as nossas escolhas.',
	'A nossa maior glória não reside no fato de nunca cairmos, mas sim em levantarmo-nos sempre depois de cada queda.',
	'A paz vem de dentro de você mesmo. Não a procure à sua volta.',
	'Existe apenas um canto do universo que você pode ter certeza de aperfeiçoar, que é você mesmo.',
	'O coração tem um espaço limitado. Então, vamos deixar só o amor entrar e jogar fora o rancor.',
	'Algumas pessoas ficam pelo caminho, mas outras maravilhosas também entram ao longo do trajeto.',
	'A vida é como um trem: pessoas entram e saem, paisagens novas aparecem, estações oferecem pausas.',
	'Não tenha medo de desistir do que já não te faz bem.',
	'Às vezes, precisamos de um pouco mais de coragem e de amor próprio.',
	'Não aceite nada que imponha limites ao que faz parte da sua essência.',
	'Valorize seus amigos e enfrente batalhas com eles! Eles são o time que você escolheu para jogar na vida.',
	'Se sentir medo, é sinal de que está bem próximo do desafio. Enfrente-o e descubra do que você é capaz.',
	'Já sentiu o cheiro das flores hoje? Já escutou o canto dos passarinhos? A vida preparou isto tudo para você também. Aproveite!',
	'Cada esquina da vida nos reserva uma surpresa. Descubra o que a próxima esquina reservou para você!',
	'Algumas coisas dão errado porque a vida planejou algo melhor.',
	'A vida sabe o que faz. Dê mais crédito a ela.',
	'Lições da vida: escute-as.',
	'A força mais potente do universo é a fé.',
	'Faça sua parte e não se preocupe com os outros. Acredite que Deus também fala com eles, e que eles estão tão empenhados quanto você em descobrir o sentido da vida.',
	'Há uma vida inteira diante de você. Vamos fazer uma linda história com ela?',
	'A motivação é o tipo de coisa que precisa ser reforçada todos os dias. Como? Alimentando a sua alma de boas energias e deixando o seu coração nutrido de carinho.',
	'Ninguém conquista o mundo sem uma boa noite de sono! Tire os problemas do seu travesseiro.',
	'Quantas coisas boas já aconteceram depois que tudo fugiu do controle? Os planos da vida são tão bons.',
	'A fé e a esperança são os melhores combustíveis do motor do corpo.',
	'Quando cansar, descanse, recupere energias e siga!',
	'Aquela força que você busca está dentro de você.',
	'Seja a pessoa que mais acredita em você!',
	'Nem todas as batalhas são feitas de vitória, mas todas elas são feitas de esforços, de aprendizagens e de recompensas.',
	'A primavera chegará, mesmo que ninguém mais saiba seu nome, nem acredite no calendário, nem possua jardim para recebê-la.',
];

export const goodMorningPhrases = [
	'Nesta manhã, te desejo apenas uma coisa: que você seja muito feliz! Um ótimo dia!',
	'Que o amor esteja presente do começo ao fim do seu dia!',
	'Agradeço pelo sol, pelos astros e por ter você ao meu lado! Bom dia!',
	'Tenha um bom dia, uma tarde produtiva e uma noite fantástica!',
	'Para hoje, escolha brilhar! Bom dia!',
	'Hoje será um dia lindo. Acorde e sorria!',
	'A vida é curta e o tempo passa rápido. Aproveite cada instante. Bom dia!',
	'A fé torna as coisas possíveis, não fáceis. Bom dia!',
	'A felicidade é uma forma de coragem! Tenha um lindo dia!',
	'Um simples "olá" e muito amor para que o seu dia seja iluminado. Bom dia!',
	'Quanto mais fortes forem suas provações, maiores serão suas vitórias. Bom dia!',
	'No final, as coisas que nos arrependemos são as decisões que não tomamos. Aproveite este dia sem medo e sem culpa!',
	'A realização de um sonho não chega antes do esforço. Tenha fé, coragem e força para que este dia te dê muito orgulho!',
	'São nos pequenos milagres que a vida nos proporciona que encontramos razões para seguir em frente. Bom dia!',
	'Não se compare com os outros. Ser único e especial é o que vai te distinguir em sua caminhada para o sucesso. Bom dia!',
	'Não tenha medo dos desafios. Tenha medo de não tentar. Bom dia!',
	'Bom dia! Para hoje, olhe para o horizonte e tenha a certeza de que tudo vai dar certo.',
	'Não seja vítima das dificuldades, tente ultrapassá-las! Bom dia!',
	'Quando você começa o dia com o coração grato, luz emana de dentro de você. Bom dia!',
	'Hoje é um ótimo dia para espalhar felicidade. Bom dia!',
	'A cada manhã nós renascemos. O que fazemos hoje é o que mais importa! Bom dia!',
	'Erros são as provas de que estamos tentando. Bom dia!',
	'A vida é muito curta para começar o dia com pedaços partidos de ontem. Tenha um ótimo dia!',
	'Um novo dia sempre revela uma nova força e um novo pensamento. Bom dia!',
	'O dia de hoje nunca mais vai se repetir. Faça o melhor dele. Bom dia!',
	'Bom café e boa fé. Bom dia!',
	'No dia de hoje, plante memórias e colha histórias. Bom dia!',
	'O mundo é perfeito para quem já acorda bem disposto. Bom dia!',
	'Eu te amo, mesmo antes de você tomar a sua primeira xícara de café. Bom dia, meu amor.',
	'Vencedores não são pessoas que nunca falham, são pessoas que nunca desistem. Tenha um dia inspirador!',
	'Cerque-se de pessoas que acreditam e lutam por você. Bom dia!',
	'Esteja presente em cada momento da sua vida, antes que estes momentos se tornem apenas lembranças. Bom dia!',
	'Os limites que impomos sobre nós podem se tornar verdadeiras prisões. Sonhe alto e tenha um ótimo dia!',
	'Ao acordar, não se esqueça de agradecer a Deus pela oportunidade de viver mais um dia de amor.',
	'Espere mais de você do que das outras pessoas. Tenha um dia produtivo e inspire as pessoas ao seu redor. Bom dia!',
	'O tempo é uma dádiva. Aproveite cada momento dele e faça a diferença. Bom dia!',
	'Que a luz do Sol ilumine o seu caminho e o seu coração.<br>No dia de hoje, espalhe alegria por onde passar!<br>Tenha uma excelente manhã e um dia maravilhoso.',
	'Que os seus sonhos te levem para onde o seu coração esteja feliz. Bom dia!',
	'Não se esqueça que a esperança é muito mais poderosa que o medo. Bom dia!',
	'Às vezes, tudo que precisamos é encarar a vida com mais leveza e menos seriedade. Bom dia!',
	'Se alguém te diz que você não é capaz de fazer alguma coisa, prove o contrário atingido o sucesso. Tenha um dia produtivo!',
	'Nada é impossível quando Deus está ao nosso lado. Bom dia!',
	'Um novo dia',
	'<br>Uma nova aventura',
	'<br>Um novo começo.',
	'Um grande final pode não ser decidido, mas um começo criativo pode ser planejado e alcançado. Bom dia! Tenha uma manhã produtiva!',
	'Acorde e faça durante o dia algo que você possa ter orgulho durante a noite.',
	'Não importa quão ruim tenha sido o dia que passou. Hoje você tem a chance de fazer a diferença e trazer a felicidade para a sua vida. Tenha um dia excepcional.',
	'Que tal começarmos esta manhã com uma atitude positiva e pensamentos de felicidade? Bom dia, meus amigos!',
	'Que o seu dia seja repleto de alegrias e muito amor. Bom dia!',
	'A cada nova manhã, nasce uma nova oportunidade de melhorar o mundo. Bom dia!',
	'Espero que sua manhã seja tão radiante quanto o seu lindo sorriso.',
	'Minha vida, acordar com você é ter a certeza de que adormeci ao lado de um anjo. Bom dia!',
	'Bom dia, amor. Você emana uma luz maior do que a do próprio Sol nesta manhã.',
	'Amor da minha vida, ter você ao meu lado é o maior privilégio da minha vida. Tenha um excelente dia.',
	'Só é um “bom dia” quando acordo com você ao meu lado.',
	'Esperança deve ser a palavra de ordem a cada manhã. Confie em Deus e tenha um dia abençoado!',
	'Que hoje você acorde com força para lutar todas as batalhas que possam vir ao seu encontro. Tenha um bom dia!',
	'Ilumine o seu dia com pensamentos positivos e espalhe alegria por onde passar. Bom dia!',
	'Nasci para ser feliz, não para ser perfeito. Bom dia!',
	'Bom dia, família. Que hoje seja mais um dia de muita alegria e gratidão para todos nós! Amo vocês!',
	'Nesta manhã, tenha a certeza que estou pensando em você. Bom dia, vida.',
	'Bom dia princesa, tenha um lindo dia com muito amor e conquistas. Te amo.',
	'Mesmo distante, saiba que estou sempre ao seu lado. Bom dia, meu amor.',
	'O que eu mais quero é passar o dia ao seu lado. Bom dia, minha princesa.',
	'Mais um dia que acordo com você em meus pensamentos. Bom dia, meu amor mais lindo.',
	'Que hoje seja um dia tão especial e maravilhoso quanto você! Bom dia!',
	'Você deve ter sido um grão de café em vidas passadas, porque eu não consigo começar o meu dia sem você!',
	'Sabe aquelas manhãs que acordamos rejuvenescidos e cheios de energia? Pois é, eu também não.',
	'O bocejo da manhã é o nosso corpo gritando: "Quero café!".',
	'Bom dia! Acordar com um pensamento positivo pela manhã pode mudar o rumo de todo o seu dia.',
	'Coisas boas estão à sua espera nesta manhã. Acredite, vença e conquiste! Bom dia!',
	'Bom dia! Ser feliz é apenas uma questão de mudar a nossa atitude perante às nossas dificuldades.',
	'A maneira que iniciamos a nossa manhã vai determinar a forma como o nosso dia será. Bom dia!',
	'Hoje, sorria para a vida e veja ela sorrir de volta para você. Tenha uma manhã linda e abençoada!',
	'Aproveite a vida da forma mais plena que ela se apresentar para você hoje. Bom dia!',
	'O maior presente das nossas vidas é poder acordar e experimentar um novo raiar de sol. Aproveite este dia ao máximo.',
	'Os raios de sol são ainda mais belos quando estamos apaixonados. Bom dia, meu amor!',
	'Já dizia o grande poeta: “gentileza gera gentileza”. Bom dia!',
	'Que Deus seja a sua fortaleza e te garanta uma dia abençoado.',
	'Nunca deixe de confiar nos planos de Deus. Ele está no comando da sua vida e está preparando um novo dia maravilhoso para você. Bom dia.',
	'Bom dia, grupo mais lindo. Que hoje o dia de vocês seja repleto de aventuras, sorrisos sinceros e cervejas geladas.',
	'Que no seu dia prevaleça a felicidade. Tenha um ótimo dia!',
	'Existem incontáveis maravilhas a sua espera no dia de hoje. Confie em Deus e em suas palavras para receber suas inúmeras bênçãos.',
	'Que o seu dia seja florido e cheio de alegrias. Bom dia!',
	'Que as suas baterias estejam recarregadas para um dia de muita energia e produtividade. Bom dia!',
	'Hoje é o único dia que você tem a chance de fazer algo de bom acontecer. É por isso que chamamos ele de ‘presente’. Tenha um ótimo dia!',
	'Escrevi um pedido e atirei no mar. Que o dia passe rápido e a noite devagar.',
	'Existem muitas coisas que fazem a vida valer a pena, e ter amigos como você é uma delas. Tenha um dia maravilhoso!',
	'Sorrisos sinceros, palavras de gentileza e um coração leve. Isso é o que desejo para o seu dia!',
	'Não se arrependa do que você fez ontem. Hoje é um novo dia para recomeçar a vida e deixar tudo de errado no passado. Um bom dia!',
	'Hoje você tem uma nova oportunidade de sorrir para a vida. Bom dia!',
	'Um sorriso no rosto pela manhã é o segredo para a felicidade ao longo do dia! Tudo vai dar certo, acredito nisto. Bom dia!',
	'Suas escolhas pela manhã são essenciais para você mudar todo o seu destino. Bom dia!',
	'O segredo da felicidade está em saber que você pode mudar tudo aquilo à sua volta, mudando apenas a atitude com que você encara a vida. Tenha um excelente dia!',
	'Hoje você tem uma nova oportunidade de compartilhar alegria para todas as pessoas à sua volta. Bom dia!',
	'Que o seu dia seja tão maravilhoso como foi a nossa noite de ontem!',
	'Não espere que as respostas caiam do céu. Comece a busca por elas hoje. Bom dia!',
	'Você não precisa de muito para mudar o mundo hoje. Seja feliz e trate as pessoas com gentileza e educação. Tenha um ótimo dia!',
	'Você constrói a sua felicidade, ela não depende de mais ninguém. Bom dia!',
	'Hoje é um novo dia para tentar mais uma vez. Desistir de primeira é para os fracos.',
	'Pense nas suas conquistas de ontem para a motivação de que hoje novas estarão a caminho. Bom dia!',
	'Não se esqueça que a receita para o sucesso está no equilíbrio. Tenha um ótimo dia!',
	'Ao acordar, respire fundo e encontre sua paz interior!',
	'Cada dia tem seu lugar e sua função! Aprenda com o ontem e viva o hoje!',
	'Para boas recompensas, não há atalhos. Seja produtivo no dia de hoje. Bom dia!',
	'Todas as manhãs são novas oportunidades para levantarmos a cabeça e corrermos atrás daquilo que desejamos. Bom dia!',
	'Ficar na cama sonhando é maravilhoso, mas levantar e lutar para conquistar os seus sonhos é ainda melhor!',
	'Os dias difíceis passam e o sol continua brilhando a cada amanhecer. Assim como ele, a alegria sempre retorna aos nossos corações! Desejo um dia luminoso para você!',
	'Não se renda! Deus não coloca no nosso caminho nenhum obstáculo que seja maior que a nossa força!',
	'Não existe amor mais importante do que aquele que sentimos por nós mesmos. Bom dia!',
	'Bom dia, pessoal! Mais uma manhã para olhar para o alto e agradecer a maravilha que é estar vivo!',
	'A vida vale a pena quando temos amigos do coração, a família reunida e muita coragem para enfrentar qualquer problema. Um dia cheio de amor e inspiração para todos!',
	'Não há dia mais importante do que hoje! Bom mesmo é sabermos aproveitar o momento presente com um sorriso no rosto.',
	'Prepare o seu melhor sorriso e receba mais um dia com a mente aberta e o espírito positivo!',
	'Que a graça do Senhor abençoe o seu dia para que ele seja iluminado e com muitas alegrias.',
	'Quando você começa o seu dia com um coração repleto de gratidão, a luz ilumina toda a sua jornada.',
	'Tem dias que precisamos criar os nossos próprios raios de sol. Bom dia!',
	'Todos os dias podem não ser bons. Mas existe sempre algo de bom em cada dia.',
	'Não olhe para trás. Hoje é um novo dia para você recomeçar!',
	'Eu amo o cheiro de possibilidades pela manhã!',
	'Acorde com determinação e vá para cama com satisfação. Bom dia!',
	'Pare de pensar no que pode dar errado e foque no que pode dar certo. Tenha um bom dia!',
	'Hoje é o seu dia! Aproveite a jornada e não se esqueça dos seus objetivos.',
	'Os erros melhoram as suas experiências e as experiências diminuem os seus erros. Tenha um bom dia!',
	'Ame a vida que você vive.<br>Viva a vida que você ama.<br>Bom dia!',
	'A vida sempre te dá uma segunda chance. Bom dia!',
	'Quando acordar esta manhã, olhe para o espelho e dê um largo sorriso. Este é o segredo mais divino para uma vida plena!',
	'Você não deve ser perfeito para começar, mas você deve começar para alcançar a perfeição. Tenha um ótimo dia!',
	'Só de pensar em você, o meu dia se torna mais iluminado. Bom dia!',
	'Ontem já passou, amanhã é um mistério e hoje é uma bênção. Bom dia!',
	'Um único passo pode ser o início de uma grande jornada. Aproveite as oportunidades que estão na sua frente e tenha um excelente dia.',
	'Você nunca viveu este dia e nunca o viverá de novo. Faça dele o melhor possível!',
	'Minhas manhãs seriam melhores se eu acordasse ao teu lado todos os dias!',
	'O seu futuro é criado quando você vive o hoje, não o amanhã!',
	'A diferença entre um bom e um mal dia está na sua atitude e determinação.',
];
